addresses:
  tezos: tz1eEnQhbwf6trb8Q8mPb2RaPkNk2rN7BKi8
  irisnet: iva1f3lapzxe7ugfex8358ufp5k8xg2yym5tpp2xje
  cosmos: cosmosvaloper1kj0h4kn4z5xvedu2nd9c4a9a559wvpuvu0h6qn
display:
  period: 2
  temperature: true
